{
 "title": "Alerts dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "FILE alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(alert_id)\nFROM alert\nWHERE\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "HOST alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_type='HOST'\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "NETWORK alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_type='NET'\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "MISC alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_type='MISC'\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "Critical severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_severity=3\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "Major severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_severity=2\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "Minor severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_severity=1\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  },
  {
   "title": "Normal severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_collr,$__interval),\n  count(*) AS \"alert_id\"\nFROM alert\nWHERE\n  alert_severity=0\n  and\n  $__timeFilter(time_collr)\nGROUP BY 1\nORDER BY $__timeGroup(time_collr,$__interval)"
    }
   ]
  }
 ]
}