openapi: 3.0.0
info:
  title: Alertflex API
  description: Alertflex public API
  version: 0.1

servers:
  - url: http://127.0.0.1:8080
    description: HTTP access
  - url: https://127.0.0.1:8181
    description: HTTPS access

paths:
  /alertflex-ctrl/rest/posture/alerts/{taskId}:
    get:
      summary: Return alerts counters 
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: Task ID
      responses:
        '200':
          description: Return alerts metrics
          content:
            application/json:
              schema:
                title: Posture alerts
                type: object
                properties:
                  criticalAlerts:
                    type: integer
                    description: Num of critical alerts
                  majorAlerts:
                    type: integer
                    description: Num of major alerts
                  minorAlerts:
                    type: integer
                    description: Num of minor alerts
                  infoAlerts:
                    type: integer
                    description: Num of info alerts
                  postureType:
                    type: string
                    enum:
                      - AppSecret
                      - DockerConfig
                      - K8sConfig
                      - AppVuln
                      - DockerVuln
                      - K8sVuln
                      - AppSbom
                      - DockerSbom
                      - CloudFormation
                      - Terraform
                      - KubeHunter
                      - ZAP
                    description: |
                      Posture type translation to scanner type:

                      AppSecret - trivy scan

                      DockerConfig - trivy scan

                      K8sConfig - trivy scan

                  target:
                    type: string
                    description: Target for Kube-hunter, ZAP and Trivy 
                  node:
                    type: string
                    description: Node name
                  host:
                    type: string
                    description: Host name where scanner is
                required:
                  - criticalAlerts
                  - majorAlerts
                  - minorAlerts
                  - infoAlerts
        '204':
          description: No Content
        
  /alertflex-ctrl/rest/posture/json/{taskId}:
    get:
      summary: Return JSON report from Trivy, ZAP and Kube-Hunter
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: Task ID
      responses:
        '200':
          description: Return id of task
          content:
            application/json:
              schema:
                title: JSON object
                type: object
        '204':
          description: No Content

  /alertflex-ctrl/rest/posture/status/{nodeId}:
    get:
      summary: Return status of sensors and scanners grid for Node in JSON format
      parameters:
        - in: path
          name: nodeId
          schema:
            type: string
          required: true
          description: Node ID/Name
      responses:
        '200':
          description: Return status
          content:
            application/json:
              schema:
                title: JSON object
                type: object
        '204':
          description: No Content

  /alertflex-ctrl/rest/posture:
    post:
      summary: Create new posture task
      requestBody:
        content:
          application/json:
            schema:
              title: Posture task
              type: object
              properties:
                delay:
                  type: integer
                  description: Delay of scan process
                postureType:
                    type: string
                    enum:
                      - AppSecret
                      - DockerConfig
                      - K8sConfig
                      - AppVuln
                      - DockerVuln
                      - K8sVuln
                      - AppSbom
                      - DockerSbom
                      - CloudFormation
                      - Terraform
                      - KubeHunter
                      - ZAP
                    description: |
                      Posture type translation to scanner type:

                      AppSecret - trivy scan

                      DockerConfig - trivy scan

                      K8sConfig - trivy scan

                target:
                  type: string
                  description: Target for Kube-Hunter, ZAP and Trivy 
                host:
                  type: string
                  description: Host name where scanner is
                node:
                  type: string
                  description: Node name
                project:
                  type: string
                  description: Project Id
              required:
                - project
                - node
                - host
                - postureType
                - delay
      responses:
        '200':
          description: Return id of task
          content:
            application/json:
              schema:
                title: Task Id
                type: object
                properties:
                  taskId:
                    type: string
                    description: UUID of task
                required:
                  - taskId
        '404':
          description: Return error
          content:
            application/json:
              schema:
                title: Error
                type: object
                properties:
                  error:
                    type: string
                    description: error of task
                required:
                  - error
      
