-- do not change any settings

CREATE TABLE `alert` (
  `alert_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `alert_uuid` char(37) NOT NULL DEFAULT '',
  `ref_id` varchar(255) NOT NULL DEFAULT '',
  `node` varchar(255) NOT NULL DEFAULT '',
  `probe` varchar(512) NOT NULL DEFAULT '',
  `categories` varchar(1024) NOT NULL DEFAULT '',
  `description` varchar(1024) NOT NULL DEFAULT '',
  `alert_severity` int(10) unsigned NOT NULL DEFAULT '0',
  `alert_source` varchar(32) NOT NULL DEFAULT '',
  `alert_type` varchar(32) NOT NULL DEFAULT '',
  `event_id` varchar(512) NOT NULL DEFAULT '',
  `event_severity` varchar(255) NOT NULL DEFAULT '',
  `location` varchar(1024) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT '',
  `action` varchar(256) NOT NULL DEFAULT '',
  `filter` varchar(512) NOT NULL DEFAULT '',
  `info` varchar(1024) NOT NULL DEFAULT '',
  `src_ip` varchar(128) NOT NULL DEFAULT '',
  `dst_ip` varchar(128) NOT NULL DEFAULT '',
  `src_hostname` varchar(512) NOT NULL DEFAULT '',
  `dst_hostname` varchar(512) NOT NULL DEFAULT '',
  `src_port` int(10) unsigned NOT NULL DEFAULT '0',
  `dst_port` int(10) unsigned NOT NULL DEFAULT '0',
  `file_name` varchar(1024) NOT NULL DEFAULT '',
  `reg_value` varchar(512) NOT NULL DEFAULT '',
  `hash_md5`  varchar(128) NOT NULL DEFAULT '',
  `hash_sha1`	varchar(128) NOT NULL DEFAULT '',
  `hash_sha256`	varchar(512) NOT NULL DEFAULT '',
  `process_id`	int(10),
  `process_name` varchar(512) NOT NULL DEFAULT '',
  `process_cmdline` varchar(512) NOT NULL DEFAULT '',
  `process_path` varchar(1024) NOT NULL DEFAULT '',
  `url_hostname` varchar(512) NOT NULL DEFAULT '',
  `url_path` varchar(1024) NOT NULL DEFAULT '',
  `container_id` varchar(512) NOT NULL DEFAULT '',
  `container_name` varchar(512) NOT NULL DEFAULT '',
  `cloud_instance` varchar(1024) NOT NULL DEFAULT '',
  `user_name` varchar(512) NOT NULL DEFAULT '',
  `agent_name` varchar(512) NOT NULL DEFAULT '',
  `incident_ext` varchar(512) NOT NULL DEFAULT '',
  `time_event` varchar(512) NOT NULL DEFAULT '',
  `time_collr` datetime DEFAULT NULL,
  `time_cntrl` datetime DEFAULT NULL,
  PRIMARY KEY (`alert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `node_alerts` (
  `rec_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ref_id` varchar(150) NOT NULL DEFAULT '',
  `node` varchar(255) NOT NULL DEFAULT '',
  `host` varchar(255) NOT NULL,
  `crs_agg` bigint unsigned NOT NULL DEFAULT '0',
  `crs_filter` bigint unsigned NOT NULL DEFAULT '0',
  `crs_s0` bigint unsigned NOT NULL DEFAULT '0',
  `crs_s1` bigint unsigned NOT NULL DEFAULT '0',
  `crs_s2` bigint unsigned NOT NULL DEFAULT '0',
  `crs_s3` bigint unsigned NOT NULL DEFAULT '0',
  `hids_agg` bigint unsigned NOT NULL DEFAULT '0',
  `hids_filter` bigint unsigned NOT NULL DEFAULT '0',
  `hids_s0` bigint unsigned NOT NULL DEFAULT '0',
  `hids_s1` bigint unsigned NOT NULL DEFAULT '0',
  `hids_s2` bigint unsigned NOT NULL DEFAULT '0',
  `hids_s3` bigint unsigned NOT NULL DEFAULT '0',
  `nids_agg` bigint unsigned NOT NULL DEFAULT '0',
  `nids_filter` bigint unsigned NOT NULL DEFAULT '0',
  `nids_s0` bigint unsigned NOT NULL DEFAULT '0',
  `nids_s1` bigint unsigned NOT NULL DEFAULT '0',
  `nids_s2` bigint unsigned NOT NULL DEFAULT '0',
  `nids_s3` bigint unsigned NOT NULL DEFAULT '0',
  `waf_agg` bigint unsigned NOT NULL DEFAULT '0',
  `waf_filter` bigint unsigned NOT NULL DEFAULT '0',
  `waf_s0` bigint unsigned NOT NULL DEFAULT '0',
  `waf_s1` bigint unsigned NOT NULL DEFAULT '0',
  `waf_s2` bigint unsigned NOT NULL DEFAULT '0',
  `waf_s3` bigint unsigned NOT NULL DEFAULT '0',
  `time_of_survey` datetime DEFAULT NULL,
  PRIMARY KEY (`rec_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `node_monitor` (
  `rec_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ref_id` varchar(150) NOT NULL DEFAULT '',
  `node` varchar(255) NOT NULL DEFAULT '',
  `host` varchar(255) NOT NULL,
  `events_crs` bigint unsigned NOT NULL DEFAULT '0',
  `events_hids` bigint unsigned NOT NULL DEFAULT '0',
  `events_nids` bigint unsigned NOT NULL DEFAULT '0',
  `events_waf` bigint unsigned NOT NULL DEFAULT '0',
  `log_counter` bigint unsigned NOT NULL DEFAULT '0',
  `log_volume` bigint unsigned NOT NULL DEFAULT '0',
  `stat_counter` bigint unsigned NOT NULL DEFAULT '0',
  `stat_volume` bigint unsigned NOT NULL DEFAULT '0',
  `time_of_survey` datetime DEFAULT NULL,
  PRIMARY KEY (`rec_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;