apiVersion: 1

datasources:
  - name: AfeventsMySQL
    type: mysql
    url: localhost:3306
    database: afevents
    user: _db_user
    secureJsonData:
      password: _db_pwd
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
  - name: AlertflexMySQL
    type: mysql
    url: localhost:3306
    database: alertflex
    user: _db_user
    secureJsonData:
      password: _db_pwd
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+